cc_library(
  name = 'tencent_img',
  srcs = [
    'TencentImg.cc',
  ],
  deps = [
    '//common/encode:encode',
  ]
)

#cc_binary(
#  name = 'test',
#  srcs = [
#    'test.cc',
#  ],
#  deps = [
#    ':tencent_img',
#  ]
#)
