proto_library(
    name = 'InteractIpc',
    srcs = [ 
        'InteractIpc.proto'
    ],  
    deps = [ 
    ]   
)

proto_library(
    name = 'RecordIpc',
    srcs = [ 
        'RecordIpc.proto'
    ],  
    deps = [ 
    ]   
)
