cc_binary(
    name = 'hello',
    srcs = 'main.cc',
    deps = [
        '//common:hello_blade',
    ]
)

cc_binary(
    name = 'test_proto',
    srcs = 'test_proto.cc',
    deps = [
        '//proto/hello_proto:hello_proto',
    ]
)
