cc_binary(
  name = 'account.cgi',
  srcs = [
    'account_cgi.cc',
  ],
  deps = [
    '//cgi/lib:cgi',
    '//thirdparty/glog:glog',
    '//common/cgi_utils:CgiUtils'
  ]
)

cc_binary(
  name = 'follow.cgi',
  srcs = [
    'follow_cgi.cc',
  ],
  deps = [
    '//cgi/lib:cgi',
    '//thirdparty/glog:glog',
    '//common/cgi_utils:CgiUtils'
  ]
)

cc_binary(
  name = 'profile.cgi',
  srcs = [
    'profile_cgi.cc',
  ],
  deps = [
    '//cgi/lib:cgi',
    '//thirdparty/glog:glog',
    '//common/cgi_utils:CgiUtils',
    '//common/tencent_img:TencentImg'
  ]
)

cc_binary(
  name = 'business.cgi',
  srcs = [
    'business_cgi.cc',
  ],
  deps = [
    '//thirdparty/glog:glog',
    '//common/cgi_utils:CgiUtils',
    '//cgi/lib:cgi',
  ]
)
