cc_binary(
  name = 'test.cgi',
  srcs = [
    'test.cc',
  ],
  deps = [
    '//cgi/lib:cgi',
    '//thirdparty/glog:glog',
    '//common/cgi_utils:CgiUtils'
  ]
)

cc_binary(
  name = 'account.cgi',
  srcs = [
    'account.cc',
  ],
  deps = [
    '//cgi/lib:cgi',
    '//thirdparty/glog:glog',
    '//common/cgi_utils:CgiUtils'
  ]
)
