cc_library(
  name = 'AppComm',
  srcs = [
    #'ParseCgiReq.cc',
    'RedisKeys.cc',
    'FollowApi.cc',
    'ProfileApi.cc',
    'InteractApi.cc',
    'RecordApi.cc',
    'CgiCode.cc',
    #'Account.cc',
    #'Business.cc',
  ],
  deps = [
    #'//proto:CgiReqProto',
    #'//proto:cache_data_proto',
    '//proto:FollowProto',
    '//proto:InteractProto',
    '//proto:RecordProto',
    '//proto:ProfileProto',
    #'//common/redis_utils:RedisUtils',
    #'//common/encode:encode',
    #'//common/sms:sms',
  ]
)

