cc_binary(
  name = 'RecordServer',
  srcs = [
    'main.cc',
    'worker.cc'
  ],
  deps = [ 
    '//service/record/proto:RecordConf',
    '//common/app:AppComm',
    '//thirdparty/glog:glog',
  ]   
)

