proto_library(
    name = 'CgiReqProto',
    srcs = [ 
        'CgiReq.proto'
    ],  
    deps = [ 
      #'//common/rpc:qzone_rpc_service_proto',
    ]   
)

proto_library(
    name = 'UserProto',
    srcs = [ 
        'user.proto'
    ],  
    deps = [ 
    ]   
)


# proto_library(
#     name = 'InteractProto',
#     srcs = [ 
#         'interact.proto'
#     ],  
#     deps = [ 
#     ]   
# )
# 
# proto_library(
#     name = 'RecordProto',
#     srcs = [ 
#         'record.proto'
#     ],  
#     deps = [ 
#     ]   
# )
