proto_library(
    name = 'cgi_req_proto',
    srcs = [ 
        'CgiReq.proto'
    ],  
    deps = [ 
      #'//common/rpc:qzone_rpc_service_proto',
    ]   
)

proto_library(
    name = 'cache_data_proto',
    srcs = [ 
        'CacheData.proto'
    ],  
    deps = [ 
    ]   
)
