cc_binary(
  name = 'account_tool',
  srcs = [
    'account_tool.cc',
  ],
  deps = [
    '//cgi/lib:cgi',
    '//common/app:AppComm',
    '//thirdparty/gflags:gflags',
    '//common/redis_utils:RedisUtils',
  ]
)

cc_binary(
  name = 'profile_tool',
  srcs = [
    'profile_tool.cc',
  ],
  deps = [
    '//cgi/lib:cgi',
    '//common/app:AppComm',
    '//thirdparty/gflags:gflags',
    '//common/redis_utils:RedisUtils',
  ]
)
