cc_binary(
  name = 'get_account',
  srcs = [
    'get_account.cc',
  ],
  deps = [
    '//cgi/lib:cgi',
    '//thirdparty/gflags:gflags',
    '//common/cgi_utils:CgiUtils'
  ]
)

cc_binary(
  name = 'del_account',
  srcs = [
    'del_account.cc',
  ],
  deps = [
    '//cgi/lib:cgi',
    '//thirdparty/gflags:gflags',
    '//common/cgi_utils:CgiUtils'
  ]
)
